import type { V2ClientExperience } from "@/types/v2";

export const v2ClientExperiences: readonly V2ClientExperience[] = [
  {
    id: "exp-healthcare-multi-branch",
    slug: "multi-location-clinic-expansion-modelling",
    title: "Multi-Location Clinic Expansion Financial Modelling",
    anonymousBusinessType: "Multi-Specialty Healthcare Network in Calicut",
    shortPreview: "Structured break-even patient volume targets and pre-opening capital requirements for a second clinic facility.",
    industryIds: ["hospitals"],
    problemIds: ["prob-healthcare-expansion"],
    serviceIds: ["business-advisory", "virtual-cfo"],
    published: true,
    featured: true,
    priority: 1,
    publishedAt: "2024-01-15",
  },
  {
    id: "exp-mfg-cost-control",
    slug: "industrial-plant-cost-center-overhead-allocation",
    title: "Industrial Plant Cost Center & Overhead Allocation",
    anonymousBusinessType: "Automotive Component Manufacturer in Malappuram",
    shortPreview: "Established activity-based cost centers isolating loss-making product lines and optimizing plant overhead absorption.",
    industryIds: ["manufacturers"],
    problemIds: ["prob-mfg-margin-visibility"],
    serviceIds: ["business-advisory", "accounting-bookkeeping"],
    published: true,
    featured: true,
    priority: 2,
    publishedAt: "2024-02-10",
  },
  {
    id: "exp-real-estate-rera",
    slug: "rera-escrow-quarterly-audit-certification",
    title: "RERA Escrow Quarterly Audit & Certificate Verification",
    anonymousBusinessType: "Residential Apartment Developer in Kozhikode",
    shortPreview: "Synchronized construction milestone progress certificates with RERA Form 3 escrow withdrawal filings.",
    industryIds: ["real-estate"],
    problemIds: ["prob-re-project-cashflow"],
    serviceIds: ["compliance", "audit-assurance"],
    published: true,
    featured: true,
    priority: 3,
    publishedAt: "2024-03-05",
  },
  {
    id: "exp-retail-inventory",
    slug: "multi-store-inventory-turnover-cash-flow-optimization",
    title: "Multi-Store Inventory Turnover & Cash Flow Optimization",
    anonymousBusinessType: "Regional Consumer Goods Retail Chain",
    shortPreview: "Audit of FSN stock velocity across 8 branch outlets, releasing working capital locked in dead stock.",
    industryIds: ["retail-wholesalers"],
    problemIds: ["prob-retail-inventory-capital"],
    serviceIds: ["business-advisory", "virtual-cfo"],
    published: true,
    featured: true,
    priority: 4,
    publishedAt: "2024-03-20",
  },
];
