import type { V2Service } from "@/types/v2";

export const v2Services: readonly V2Service[] = [
  {
    id: "virtual-cfo",
    slug: "virtual-cfo",
    title: "Virtual CFO Services",
    description: "Strategic financial leadership, cash flow management, and board reporting for growing companies.",
    problemIds: ["prob-growth-without-cash-flow", "prob-healthcare-expansion"],
    industryIds: ["hospitals", "manufacturers", "retail-wholesalers"],
    relatedServiceSlugs: ["business-advisory", "audit-assurance"],
    published: true,
    featured: true,
    priority: 1,
  },
  {
    id: "business-advisory",
    slug: "business-advisory",
    title: "Business Advisory",
    description: "Capital expansion modeling, break-even analysis, and financial decision structuring.",
    problemIds: ["prob-healthcare-expansion", "prob-cross-capex-decision", "prob-mfg-margin-visibility"],
    industryIds: ["hospitals", "manufacturers", "real-estate", "retail-wholesalers", "education", "pharma", "textiles"],
    relatedServiceSlugs: ["virtual-cfo", "corporate-advisory"],
    published: true,
    featured: true,
    priority: 2,
  },
  {
    id: "audit-assurance",
    slug: "audit-assurance",
    title: "Audit & Assurance",
    description: "Statutory audits, internal financial control reviews, and compliance certifications.",
    problemIds: ["prob-healthcare-cashflow", "prob-nbfc-compliance-workload", "prob-pharma-inventory-working-capital"],
    industryIds: ["hospitals", "manufacturers", "nbfcs", "education", "pharma"],
    relatedServiceSlugs: ["compliance", "tax-planning"],
    published: true,
    featured: true,
    priority: 3,
  },
  {
    id: "tax-planning",
    slug: "tax-planning",
    title: "Tax Planning & Direct Taxation",
    description: "Corporate tax optimization, Section 11/12A trust tax exemptions, and R&D tax credit structuring.",
    problemIds: ["prob-edu-fee-cashflow", "prob-textiles-seasonal-working-capital", "prob-pharma-inventory-working-capital"],
    industryIds: ["education", "textiles", "pharma", "hospitals"],
    relatedServiceSlugs: ["compliance", "business-advisory"],
    published: true,
    featured: true,
    priority: 4,
  },
  {
    id: "compliance",
    slug: "compliance",
    title: "GST & Regulatory Compliance",
    description: "Turn-key GST filing, inverted duty structure refunds, RERA compliance, and RBI regulatory return preparation.",
    problemIds: ["prob-re-project-cashflow", "prob-nbfc-compliance-workload", "prob-textiles-seasonal-working-capital"],
    industryIds: ["real-estate", "nbfcs", "textiles", "retail-wholesalers"],
    relatedServiceSlugs: ["audit-assurance", "tax-planning"],
    published: true,
    featured: true,
    priority: 5,
  },
  {
    id: "corporate-advisory",
    slug: "corporate-advisory",
    title: "Corporate & M&A Advisory",
    description: "Financial due diligence, joint venture structuring, and capital debt evaluation.",
    problemIds: ["prob-cross-capex-decision"],
    industryIds: ["manufacturers", "real-estate"],
    relatedServiceSlugs: ["business-advisory", "virtual-cfo"],
    published: true,
    featured: false,
    priority: 6,
  },
  {
    id: "accounting-bookkeeping",
    slug: "accounting-bookkeeping",
    title: "Accounting & Bookkeeping",
    description: "Systematic ledger maintenance, activity-based costing, and monthly financial reporting.",
    problemIds: ["prob-mfg-margin-visibility"],
    industryIds: ["manufacturers", "retail-wholesalers"],
    relatedServiceSlugs: ["virtual-cfo", "audit-assurance"],
    published: true,
    featured: false,
    priority: 7,
  },
];
